@echo off
cd /d "%~dp0"
echo Stopping old Timesheet processes...
taskkill /f /im pythonw.exe >nul 2>&1
echo Clearing cache...
if exist timesheet\__pycache__ rmdir /s /q timesheet\__pycache__
echo Pulling latest updates...
git pull
echo Starting Timesheet...
start "" /D "%~dp0" pythonw -m flask --app timesheet.app:create_app run --host 0.0.0.0 --port 5000
echo Timesheet started at http://127.0.0.1:5000
timeout /t 3
